dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.8.1

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933

- sudo apt-get install -y zip unzip
- wget https://releases.hashicorp.com/terraform/0.9.8/terraform_0.9.8_linux_amd64.zip
- unzip terraform_0.9.8_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- terraform --version



script:
- terraform init
- terraform apply
- terraform destroy




branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
