#Ubuntu VM created by Google compute engine
## https://docs.travis-ci.com/user/reference/overview/
dist: trusty

# If you need a more customizable environment running in a virtual machine :ubuntu environment
sudo: required

services:
 - docker

 #Specifies language
language: go

# language version
go:
- 1.8.1

install:
# This script is used by the Travis build to install terraform packages
- sudo apt-get install -y zip unzip
- wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- unzip terraform_0.11.7_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- terraform --version


before_script:
# creates executable file
- go build



jobs:
  include:
  #stage 1 to execute positive test case
    - stage: Positive_TestCases
      script:
     #cp to copy build code to folder containing config file
        - sudo cp terraform-provider-opentelekomcloud /Positive_TestCases
        - terraform init ./Positive_TestCases
        - terraform apply -auto-approve ./Positive_TestCases
        - terraform destroy -force ./Positive_TestCases


  # stage 2 to execute negative test case

    - stage: Negative_TestCases
      script:
     #cp to copy build code to folder containing config file
        - sudo cp terraform-provider-opentelekomcloud /Negative_TestCases
        - terraform init ./Negative_TestCases
        - terraform apply -auto-approve ./Negative_TestCases
        - terraform destroy -force ./Negative_TestCases

# script to execute terraform command to create a resource

notifications:

  email:
    recipients:
      - rohini.burde@click2cloud.net
  ##  - apurva.dhoble@click2cloud.net
  ##  - disha.wani@click2cloud.net
  ##  - sapan.vaswani@click2cloud.net
    on_success: always
    on_failure: always


branches:
  only:
  - master

matrix:
# the build won’t be marked as finished until they have completed, use fast_finish to mark them as finish
    fast_finish: true
    allow_failures:
    - stage: Negative_TestCases
