dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.8.1

install:
# This script is used by the Travis build to install terraform packages
- sudo apt-get install -y zip unzip
- wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- unzip terraform_0.11.7_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- terraform --version

before_script:
# creates executable file
- go build


script:

- terraform init /VPC_resource_testcase1/vpc_route.tf
- terraform apply -auto-approve /VPC_resource_testcase1/vpc_route.tf
- terraform destroy -force /VPC_resource_testcase1/vpc_route.tf

- terraform init /VPC_resource_testcase1/vpc_route_withInvalidParameters.tf
- terraform apply -auto-approve /VPC_resource_testcase1/vpc_route_withInvalidParameters.tf
- terraform destroy -force /VPC_resource_testcase1/vpc_route_withInvalidParameters.tf





branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
