dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.8.1

install:
# This script is used by the Travis build to install terraform packages
- sudo apt-get install -y zip unzip
- wget https://releases.hashicorp.com/terraform/0.9.8/terraform_0.9.8_linux_amd64.zip
- unzip terraform_0.9.8_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- terraform --version

before_script:
# creates executable file
- go build


script:

- terraform init
# - terraform apply -auto-approve
# - terraform destroy -force



branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
