#Ubuntu VM created by Google compute engine
## https://docs.travis-ci.com/user/reference/overview/
dist: trusty

# If you need a more customizable environment running in a virtual machine :ubuntu environment
sudo: enabled

services:
 - docker

 #Specifies language
language: go

# language version
go:
- 1.8.1

install:
# This script is used by the Travis build to install terraform packages
- sudo apt-get install -y zip unzip
- wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- unzip terraform_0.11.7_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- terraform --version


before_script:
# creates executable file
- go build
- ls



jobs:
  include:
    #- stage: testcase1
    #  script:
    #    - sudo cp terraform-provider-opentelekomcloud /examples
    #    - terraform init ./examples
    #    - terraform plan ./examples
    #    - terraform apply -auto-approve ./examples
    #    - terraform destroy -force ./examples

    - stage: testcase2
      script:
        - sudo cp terraform-provider-opentelekomcloud /Testcase2
        - terraform init ./Testcase2
        - terraform plan ./Testcase2
        - terraform apply -auto-approve ./Testcase2
        - terraform destroy -force ./Testcase2

# script to execute terraform command to create a resource

#allow_failure: always

notifications:

  email:
    recipients:
      - rohini.burde@click2cloud.net
  ##    - apurva.dhoble@click2cloud.net
  ##  - disha.wani@click2cloud.net
  ##  - sapan.vaswani@click2cloud.net
    on_success: always
    on_failure: always





branches:
  only:
  - master

matrix:
    fast_finish: true
    allow_failures:
          stage: testcase2

