#Ubuntu VM created by Google compute engine
## https://docs.travis-ci.com/user/reference/overview/
dist: trusty

# If you need a more customizable environment running in a virtual machine :ubuntu environment
sudo: enabled

services:
 - docker

 #Specifies language
language: go

# language version
go:
- 1.8.1

install:
# This script is used by the Travis build to install terraform packages
- apt-get install -y zip unzip
- wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- unzip terraform_0.11.7_linux_amd64.zip
- mv terraform /usr/local/bin/
- terraform --version


before_script:
# creates executable file
- go build


jobs:
  include:
    - stage: test
      script:
      - terraform init
      - terraform plan
      - terraform apply -auto-approve
      - terraform destroy -force


# script to execute terraform command to create a resource

#allow_failure: always

notifications:

  email:
    recipients:
      - rohini.burde@click2cloud.net
  ##    - apurva.dhoble@click2cloud.net
  ##  - disha.wani@click2cloud.net
  ##  - sapan.vaswani@click2cloud.net
    on_success: always
    on_failure: always





branches:
  only:
  - master

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  - stage: test

