# dist: trusty
# sudo: required
#services:
# - docker
#Specifies language
language: go
# language version
go:
- 1.8.1


# To install dependencies to install terraform
install:
# This script is used by the Travis build to install terraform packages
- sudo apt-get install -y zip unzip
- wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- unzip terraform_0.11.7_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- terraform --version


before_script:
# creates executable file
- go build


# script to execute terraform command to create a resource
script:

- terraform init
- terraform plan
- terraform apply -auto-approve
- terraform destroy -force

notifications:

  email:
    recipients:
      - rohini.burde@click2cloud.net
  ##    - apurva.dhoble@click2cloud.net
  ##  - disha.wani@click2cloud.net
  ##  - sapan.vaswani@click2cloud.net
    on_success: always
    on_failure: always
    template:
          - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
    format: html

 ## template:
   ##   - "%{repository_slug} (%{commit}) : %{message} %{foo} "
   ##   - "Build details: %{build_url}"





branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
